server:
  port: 8082
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: shramin_password
    url: jdbc:postgresql://localhost:5432/microservices
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql

  application:
    name: HOTEL-SERVICE
  config:
    import: optional:configserver:http://localhost:8085

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
